export declare const sunPalette: {
  primary: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    main: string;
    dark: string;
    light: string;
    alpha12: string;
    alpha20: string;
    alpha30: string;
    alpha40: string;
  };
  neutral: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    main: string;
    dark: string;
    light: string;
  };
  success: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    main: string;
    dark: string;
    alpha12: string;
    alpha20: string;
  };
  warning: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    main: string;
    dark: string;
    alpha12: string;
    alpha20: string;
  };
  danger: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    main: string;
    dark: string;
    alpha12: string;
    alpha20: string;
  };
};
export declare const radiusScale: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const spacingScale: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  xxl: number;
};
//# sourceMappingURL=palette.d.ts.map
